### ISSUE TITLE
Slim Application Error when opening 'Meal Planner' in HA

### ISSUE THREAD

**Issue by moterisma** [hassio-addons/addon-grocy#100]
# Problem/Motivation

Meal planner does not open due to a slim application error. Debug log below:
>
```
> -----------------------------------------------------------
>  Add-on version: 0.9.1
>  You are running the latest version of this add-on.
>  System: HassOS 4.15  (aarch64 / raspberrypi4-64)
>  Home Assistant Core: 0.117.0b3
>  Home Assistant Supervisor: 249
> -----------------------------------------------------------
>  Please, share the above information when looking for help
>  or support in, e.g., GitHub, forums or the Discord chat.
> -----------------------------------------------------------
> [cont-init.d] 00-banner.sh: exited 0.
> [cont-init.d] 01-log-level.sh: executing... 
> Log level is set to DEBUG
> [cont-init.d] 01-log-level.sh: exited 0.
> [cont-init.d] grocy.sh: executing... 
> [21:04:09] DEBUG: Symlinking data directory to persistent storage location...
> [cont-init.d] grocy.sh: exited 0.
> [cont-init.d] nginx.sh: executing... 
> [21:04:10] DEBUG: Requested API resource: http://supervisor/dns/info
> [21:04:10] DEBUG: Request method: GET
> [21:04:10] DEBUG: Request data: {}
> [21:04:10] DEBUG: API HTTP Response code: 200
> [21:04:10] DEBUG: API Response: {"result": "ok", "data": {"version": "2020.10.0", "version_latest": "2020.10.0", "host": "172.30.32.3", "servers": [], "locals": ["dns://192.168.1.1", "dns://fe80::1213:31ff:fece:b344"]}}
> [cont-init.d] nginx.sh: exited 0.
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> [21:04:10] INFO: Starting PHP-FPM...
> [21:04:14] INFO: Starting NGinx....
> [24/Oct/2020:21:04:38 +1100] 302 192.168.1.253, 172.30.32.1(172.30.32.2) GET / HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36)
> [24/Oct/2020:21:04:38 +1100] 200 192.168.1.253, 172.30.32.1(172.30.32.2) GET /tasks HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36)
> [24/Oct/2020:21:04:38 +1100] 200 192.168.1.253, 172.30.32.1(172.30.32.2) GET /api/system/db-changed-time HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36)
> [24/Oct/2020:21:04:38 +1100] 204 192.168.1.253, 172.30.32.1(172.30.32.2) PUT /api/user/settings/auto_night_mode_enabled HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36)
> [24/Oct/2020:21:04:39 +1100] 200 192.168.1.253, 172.30.32.1(172.30.32.2) GET /api/tasks HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36)
> [24/Oct/2020:21:04:43 +1100] 200 192.168.1.34, 172.30.32.1(172.30.32.2) GET /api/system/db-changed-time HTTP/1.1 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36)
> [24/Oct/2020:21:04:43 +1100] 200 192.168.1.34, 172.30.32.1(172.30.32.2) GET /tasks HTTP/1.1 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36)
> [24/Oct/2020:21:04:44 +1100] 200 192.168.1.34, 172.30.32.1(172.30.32.2) GET /api/system/db-changed-time HTTP/1.1 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36)
> [24/Oct/2020:21:04:44 +1100] 204 192.168.1.34, 172.30.32.1(172.30.32.2) PUT /api/user/settings/night_mode_enabled HTTP/1.1 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36)
> [24/Oct/2020:21:04:44 +1100] 204 192.168.1.34, 172.30.32.1(172.30.32.2) PUT /api/user/settings/auto_night_mode_enabled HTTP/1.1 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36)
> [24/Oct/2020:21:04:44 +1100] 204 192.168.1.34, 172.30.32.1(172.30.32.2) PUT /api/user/settings/currently_inside_night_mode_range HTTP/1.1 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36)
> [24/Oct/2020:21:04:45 +1100] 200 192.168.1.34, 172.30.32.1(172.30.32.2) GET /api/tasks HTTP/1.1 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36)
> [24/Oct/2020:21:04:47 +1100] 500 192.168.1.253, 172.30.32.1(172.30.32.2) GET /mealplan HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36)
> [24/Oct/2020:21:04:47 +1100] 200 192.168.1.253, 172.30.32.1(172.30.32.2) GET /api/system/db-changed-time HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36)
> 2020/10/24 21:04:48 [error] 1322#1322: *5 FastCGI sent in stderr: "PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 50PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name_plural' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 50PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name_plural' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 50PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4a
> 2020/10/24 21:04:48 [error] 1322#1322: *5 FastCGI sent in stderr: "ta/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name_plural' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 50PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name_plural' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 50PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name_pl
> 2020/10/24 21:04:48 [error] 1322#1322: *5 FastCGI sent in stderr: "Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name_plural' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 50PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name_plural' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 50PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name_plural' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php o
> 2020/10/24 21:04:48 [error] 1322#1322: *5 FastCGI sent in stderr: "iewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 50PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name_plural' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 50PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name_plural' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 50PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-obje
> 2020/10/24 21:04:48 [error] 1322#1322: *5 FastCGI sent in stderr: "rying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name_plural' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 50PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name_plural' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 50PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59P
> 2020/10/24 21:04:48 [error] 1322#1322: *5 FastCGI sent in stderr: "cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name_plural' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 50PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name_plural' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 50PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name_plural' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /dat
> 2020/10/24 21:04:48 [error] 1322#1322: *5 FastCGI sent in stderr: "et property 'name_plural' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 50PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name_plural' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 50PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name_plural' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 50PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message
> 2020/10/24 21:04:48 [error] 1322#1322: *5 FastCGI sent in stderr: "701e00e256798afb4ad5b8.php on line 50PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name_plural' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 50PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name_plural' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 50PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/vi
> 2020/10/24 21:04:48 [error] 1322#1322: *5 FastCGI sent in stderr: "y 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name_plural' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 50PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name_plural' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 50PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'qu_id_stock' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Notice:  Trying to get property 'name_plural' of non-object in /data/grocy/viewcache/35fef0d3cf75992e49701e00e256798afb4ad5b8.php on line 59PHP message: PHP Noti
> [24/Oct/2020:21:04:48 +1100] 200 192.168.1.253, 172.30.32.1(172.30.32.2) GET /stockjournal HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36)
> [24/Oct/2020:21:04:49 +1100] 200 192.168.1.253, 172.30.32.1(172.30.32.2) GET /api/system/db-changed-time HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36)
> [24/Oct/2020:21:04:49 +1100] 204 192.168.1.253, 172.30.32.1(172.30.32.2) PUT /api/user/settings/auto_night_mode_enabled HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36)
> [24/Oct/2020:21:04:52 +1100] 204 192.168.1.253, 172.30.32.1(172.30.32.2) PUT /api/user/settings/auto_night_mode_enabled HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36)
```

## Expected behavior

Meal planner page opens.

## Actual behavior

Slim Application Error Page Text below:
```
Slim Application Error
The application could not run because of the following error:

Details
Type: Exception
Code: 0
Message: Product does not exist
File: /var/www/grocy/services/StockService.php
Line: 105
Trace
#0 /var/www/grocy/controllers/RecipesController.php(161): Grocy\Services\StockService->GetProductDetails(158)
#1 /var/www/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Grocy\Controllers\RecipesController->MealPlan(Object(Slim\Http\ServerRequest), Object(Slim\Http\Response), Array)
#2 /var/www/grocy/vendor/slim/slim/Slim/Routing/Route.php(381): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\ServerRequest), Object(Slim\Http\Response), Array)
#3 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle(Object(Slim\Http\ServerRequest))
#4 /var/www/grocy/middleware/SessionAuthMiddleware.php(67): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#5 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(283): Grocy\Middleware\SessionAuthMiddleware->__invoke(Object(Slim\Http\ServerRequest), Object(Slim\MiddlewareDispatcher))
#6 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#7 /var/www/grocy/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#8 /var/www/grocy/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run(Object(Slim\Http\ServerRequest))
#9 /var/www/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(60): Slim\Routing\RouteRunner->handle(Object(Slim\Http\ServerRequest))
#10 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\RoutingMiddleware->process(Object(Slim\Http\ServerRequest), Object(Slim\Routing\RouteRunner))
#11 /var/www/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#12 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\ErrorMiddleware->process(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#13 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#14 /var/www/grocy/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#15 /var/www/grocy/vendor/slim/slim/Slim/App.php(199): Slim\App->handle(Object(Slim\Http\ServerRequest))
#16 /var/www/grocy/app.php(68): Slim\App->run()
#17 /var/www/grocy/public/index.php(27): require_once('/var/www/grocy/...')
#18 {main}`
```
'Recipes', 'Shopping List' and other inventory pages work as per normal.

## Steps to reproduce

Unsure how this error may have been created. Error message seems to point to a missing product that may have been deleted.

## Proposed changes

Is there a way to view the grocy database in HA to identify potential missing product/product type and re-create it to solve the issue?

**Comment by frenck** [comment]
@moterisma The Grocy Add-on v0.10.0 has been released. The main plan opens on both direct access and in ingress view inside Home Assistant.

Is the issue solved for you with this version as well?
