### ISSUE TITLE
Grocy Hass.io addon cannot be started after upgraded to version 0.2.0

### ISSUE THREAD

**Issue by jerrychong25** [hassio-addons/addon-grocy#27]
# Problem/Motivation
Failed to start Grocy Hass.io addon after upgraded from version 0.1.0 to version 0.2.0 in HA version 0.94.0 onwards.

## Expected behavior
Start Grocy Hass.io addon successfully after upgraded to version 0.2.0.

## Actual behavior
Failed to start Grocy Hass.io addon after upgraded to version 0.2.0, as per screenshot below:
<img width="628" alt="Screenshot 2019-06-11 at 11 47 24 AM" src="https://user-images.githubusercontent.com/15714095/59242780-7f6a1e00-8c3f-11e9-950d-1fac5dd7bb6e.png">

## Steps to reproduce
1. Grocy Hass.io addon in version 0.1.0.
2. Press **Upgrade** button to update latest version to 0.2.0.
3. Press **Start** button up to start Grocy as usual.
4. Failed to start.

## Proposed changes
N/A

**Comment by tjorim** [comment]
Please provide the logs.

**Comment by jerrychong25** [comment]
> Please provide the logs.

![image](https://user-images.githubusercontent.com/15714095/59283588-5f694780-8c9d-11e9-8d86-7f187efe03f9.png)

```
19-06-11 03:43:25 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-06-11 03:43:25 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
19-06-11 03:43:25 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:21093 ssl:False [Connection refused].
19-06-11 03:43:30 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-06-11 03:43:30 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
19-06-11 03:43:30 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:21093 ssl:False [Connection refused].
19-06-11 03:43:30 INFO (SyncWorker_0) [hassio.docker.homeassistant] Start homeassistant homeassistant/raspberrypi3-homeassistant with version 0.94.1
19-06-11 03:43:35 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-06-11 03:43:35 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
19-06-11 03:43:35 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:21093 ssl:False [Connection refused].
19-06-11 03:43:40 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-06-11 03:43:40 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
19-06-11 03:43:40 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:21093 ssl:False [Connection refused].
19-06-11 03:43:45 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-06-11 03:43:45 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
19-06-11 03:43:45 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:21093 ssl:False [Connection refused].
19-06-11 03:43:50 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-06-11 03:43:50 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
19-06-11 03:43:50 ERROR (MainThread) [hassio.api.proxy] Client error on WebSocket API Cannot connect to host 172.30.32.1:21093 ssl:False [Connection refused].
19-06-11 03:43:51 INFO (MainThread) [hassio.homeassistant] Detect a running Home Assistant instance
19-06-11 03:43:51 INFO (MainThread) [hassio.homeassistant] Successful run Home Assistant 0.94.1
19-06-11 03:43:55 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request initialize
19-06-11 03:43:55 INFO (MainThread) [hassio.api.proxy] WebSocket access from a0d7b954_nodered
19-06-11 03:43:55 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
19-06-11 03:43:55 INFO (MainThread) [hassio.api.proxy] Home Assistant WebSocket API request running
19-06-11 08:36:41 INFO (MainThread) [hassio.updater] Fetch update data from https://s3.amazonaws.com/hassio-version/stable.json
19-06-11 08:36:41 INFO (MainThread) [hassio.store.git] Update add-on https://github.com/hassio-addons/repository repository
19-06-11 08:36:41 INFO (MainThread) [hassio.store.git] Update add-on https://github.com/danielwelch/hassio-zigbee2mqtt repository
19-06-11 08:36:41 INFO (MainThread) [hassio.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository
19-06-11 08:36:44 INFO (MainThread) [hassio.store] Load add-ons from store: 61 all - 0 new - 0 remove
19-06-11 10:34:52 INFO (MainThread) [__main__] Initialize Hass.io setup
19-06-11 10:34:52 INFO (MainThread) [__main__] Setup HassIO
19-06-11 10:34:52 INFO (SyncWorker_0) [hassio.docker.supervisor] Attach to Supervisor homeassistant/armhf-hassio-supervisor with version 166
19-06-11 10:34:52 INFO (MainThread) [hassio.utils.gdbus] Introspect org.freedesktop.systemd1 on /org/freedesktop/systemd1
19-06-11 10:34:52 INFO (MainThread) [hassio.utils.gdbus] Connect to dbus: org.freedesktop.systemd1 - /org/freedesktop/systemd1
19-06-11 10:34:52 INFO (MainThread) [hassio.utils.gdbus] Introspect org.freedesktop.hostname1 on /org/freedesktop/hostname1
19-06-11 10:34:52 INFO (MainThread) [hassio.utils.gdbus] Connect to dbus: org.freedesktop.hostname1 - /org/freedesktop/hostname1
19-06-11 10:34:52 INFO (MainThread) [hassio.utils.gdbus] Introspect de.pengutronix.rauc on /
19-06-11 10:34:52 ERROR (MainThread) [hassio.utils.gdbus] DBus return error: b'Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name de.pengutronix.rauc was not provided by any .service files\n'
19-06-11 10:34:52 WARNING (MainThread) [hassio.dbus.rauc] Can't connect to rauc
19-06-11 10:34:52 INFO (MainThread) [hassio.host.info] Update local host information
19-06-11 10:34:52 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
19-06-11 10:34:53 INFO (MainThread) [hassio.host.services] Update service information
19-06-11 10:34:53 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
19-06-11 10:34:53 INFO (MainThread) [hassio.host.apparmor] Load AppArmor Profiles: {'hassio-supervisor'}
19-06-11 10:34:53 INFO (MainThread) [hassio.host.apparmor] AppArmor is not enabled on host
19-06-11 10:34:53 INFO (SyncWorker_1) [hassio.docker.interface] Attach to homeassistant/raspberrypi3-homeassistant with version 0.94.1
19-06-11 10:34:53 INFO (MainThread) [hassio.store.git] Load add-on /data/addons/core repository
19-06-11 10:34:53 INFO (MainThread) [hassio.store.git] Load add-on /data/addons/git/a0d7b954 repository
19-06-11 10:34:53 INFO (MainThread) [hassio.store.git] Load add-on /data/addons/git/7ad98f9c repository
19-06-11 10:34:54 INFO (MainThread) [hassio.store] Load add-ons from store: 61 all - 61 new - 0 remove
19-06-11 10:34:54 INFO (MainThread) [hassio.addons] Found 6 installed add-ons
19-06-11 10:34:54 INFO (SyncWorker_2) [hassio.docker.interface] Attach to homeassistant/armv7-addon-mosquitto with version 4.3
19-06-11 10:34:54 INFO (SyncWorker_0) [hassio.docker.interface] Attach to homeassistant/armv7-addon-samba with version 8.1
19-06-11 10:34:54 INFO (SyncWorker_5) [hassio.docker.interface] Attach to dwelch2101/zigbee2mqtt-armhf with version 1.4.0
19-06-11 10:34:54 INFO (SyncWorker_1) [hassio.docker.interface] Attach to hassioaddons/ide-armv7 with version v1.0.0
19-06-11 10:34:54 INFO (SyncWorker_7) [hassio.docker.interface] Attach to hassioaddons/node-red-armv7 with version v3.1.1
19-06-11 10:34:54 INFO (SyncWorker_11) [hassio.docker.interface] Attach to hassioaddons/grocy-armv7 with version v0.2.0
19-06-11 10:34:54 INFO (MainThread) [hassio.updater] Fetch update data from https://s3.amazonaws.com/hassio-version/stable.json
19-06-11 10:34:55 INFO (MainThread) [hassio.snapshots] Found 0 snapshot files
19-06-11 10:34:55 INFO (MainThread) [hassio.discovery] Load 1 messages
19-06-11 10:34:55 INFO (MainThread) [hassio.ingress] Load 0 ingress session
19-06-11 10:34:55 INFO (MainThread) [__main__] Run Hass.io
19-06-11 10:34:55 INFO (MainThread) [hassio.misc.dns] Start DNS port forwarding for host add-ons
19-06-11 10:34:55 INFO (MainThread) [hassio.api] Start API on 172.30.32.2
19-06-11 10:34:55 INFO (MainThread) [hassio.addons] Phase 'initialize' start 0 add-ons
19-06-11 10:34:55 INFO (MainThread) [hassio.addons] Phase 'system' start 2 add-ons
19-06-11 10:34:56 ERROR (MainThread) [hassio.addons.addon] Add-on a0d7b954_grocy have wrong options: Missing option stock in features. Got {'culture': 'en', 'currency': 'RM', 'features': {'batteries': True, 'calendar': True, 'chores': True, 'equipment': True, 'recipes': True, 'shoppinglist': True, 'tasks': True}, 'ssl': False, 'certfile': 'fullchain.pem', 'keyfile': 'privkey.pem'}
```

**Comment by Jeltel** [comment]
Having the same issues now in 0.94.1. It worked in version 0.93 (but it has other issues).

Now I'm getting a Slim Application Error:
```Slim Application Error

The application could not run because of the following error:
Details
Type: ErrorException
Message: Function name must be a string (View: /var/www/grocy/views/stockoverview.blade.php)
File: /data/grocy/viewcache/9f8b89175ea21431419b2a4d06fa295d5a75b7a6.php
Line: 1
Trace

#0 /var/www/grocy/vendor/illuminate/view/Engines/PhpEngine.php(47): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(Symfony\Component\Debug\Exception\FatalThrowableError), 2)
#1 /var/www/grocy/vendor/illuminate/view/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/grocy/...', Array)
#2 /var/www/grocy/vendor/illuminate/view/View.php(142): Illuminate\View\Engines\CompilerEngine->get('/var/www/grocy/...', Array)
#3 /var/www/grocy/vendor/illuminate/view/View.php(125): Illuminate\View\View->getContents()
#4 /var/www/grocy/vendor/illuminate/view/View.php(90): Illuminate\View\View->renderContents()
#5 /var/www/grocy/vendor/rubellum/slim-blade-view/src/Blade.php(173): Illuminate\View\View->render()
#6 /var/www/grocy/vendor/rubellum/slim-blade-view/src/Blade.php(65): Slim\Views\Blade->fetch('stockoverview', Array)
#7 /var/www/grocy/controllers/StockController.php(37): Slim\Views\Blade->render(Object(Slim\Http\Response), 'stockoverview', Array)
#8 [internal function]: Grocy\Controllers\StockController->Overview(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#9 /var/www/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#10 /var/www/grocy/vendor/slim/slim/Slim/Route.php(356): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#11 /var/www/grocy/middleware/SessionAuthMiddleware.php(57): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#12 [internal function]: Grocy\Middleware\SessionAuthMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#13 /var/www/grocy/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Grocy\Middleware\SessionAuthMiddleware), Array)
#14 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#15 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#16 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#17 /var/www/grocy/vendor/slim/slim/Slim/Route.php(334): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#18 /var/www/grocy/vendor/slim/slim/Slim/App.php(515): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#19 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#20 /var/www/grocy/vendor/slim/slim/Slim/App.php(405): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#21 /var/www/grocy/vendor/slim/slim/Slim/App.php(313): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#22 /var/www/grocy/app.php(71): Slim\App->run()
#23 /var/www/grocy/public/index.php(3): require_once('/var/www/grocy/...')
#24 {main}

Previous exception
Type: Symfony\Component\Debug\Exception\FatalThrowableError
Message: Function name must be a string
File: /data/grocy/viewcache/9f8b89175ea21431419b2a4d06fa295d5a75b7a6.php
Line: 1
Trace

#0 /var/www/grocy/vendor/illuminate/view/Engines/PhpEngine.php(43): include()
#1 /var/www/grocy/vendor/illuminate/view/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/grocy/...', Array)
#2 /var/www/grocy/vendor/illuminate/view/View.php(142): Illuminate\View\Engines\CompilerEngine->get('/var/www/grocy/...', Array)
#3 /var/www/grocy/vendor/illuminate/view/View.php(125): Illuminate\View\View->getContents()
#4 /var/www/grocy/vendor/illuminate/view/View.php(90): Illuminate\View\View->renderContents()
#5 /var/www/grocy/vendor/rubellum/slim-blade-view/src/Blade.php(173): Illuminate\View\View->render()
#6 /var/www/grocy/vendor/rubellum/slim-blade-view/src/Blade.php(65): Slim\Views\Blade->fetch('stockoverview', Array)
#7 /var/www/grocy/controllers/StockController.php(37): Slim\Views\Blade->render(Object(Slim\Http\Response), 'stockoverview', Array)
#8 [internal function]: Grocy\Controllers\StockController->Overview(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#9 /var/www/grocy/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#10 /var/www/grocy/vendor/slim/slim/Slim/Route.php(356): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#11 /var/www/grocy/middleware/SessionAuthMiddleware.php(57): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#12 [internal function]: Grocy\Middleware\SessionAuthMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#13 /var/www/grocy/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Grocy\Middleware\SessionAuthMiddleware), Array)
#14 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#15 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#16 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#17 /var/www/grocy/vendor/slim/slim/Slim/Route.php(334): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#18 /var/www/grocy/vendor/slim/slim/Slim/App.php(515): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#19 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#20 /var/www/grocy/vendor/slim/slim/Slim/App.php(405): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#21 /var/www/grocy/vendor/slim/slim/Slim/App.php(313): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#22 /var/www/grocy/app.php(71): Slim\App->run()
#23 /var/www/grocy/public/index.php(3): require_once('/var/www/grocy/...')
#24 {main}
```

And in the hassio log:
```


[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-grocy: applying... 
[fix-attrs.d] 01-grocy: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Hass.io Add-on: Grocy
 ERP beyond your fridge! A groceries & household management solution for your home
-----------------------------------------------------------
 Add-on version: 0.2.0
 You are running the latest version of this add-on.
 System: Ubuntu 18.04.2 LTS  (amd64 / qemux86-64)
 Home Assistant version: 0.94.1
 Supervisor version: 166
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] grocy.sh: executing... 
[cont-init.d] grocy.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[21:02:21] INFO: Starting PHP-FPM...
[21:02:22] INFO: Starting NGinx....
nginx: [warn] "ssl_stapling" ignored, host not found in OCSP responder "ocsp.int-x3.letsencrypt.org" in the certificate "/ssl/fullchain.pem"
[11/Jun/2019:21:02:39 +0200] 302 62.251.119.181(172.30.32.1) GET / HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0)
2019/06/11 21:02:39 [error] 902#902: *3 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: L in /data/grocy/viewcache/9f8b89175ea21431419b2a4d06fa295d5a75b7a6.php on line 1" while reading response header from upstream, client: 172.30.32.1, server: a0d7b954-grocy, request: "GET /stockoverview HTTP/1.1", upstream: "fastcgi://127.0.0.1:9001", host: "grocy.ollavogala.org"
[11/Jun/2019:21:02:39 +0200] 500 62.251.119.181(172.30.32.1) GET /stockoverview HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0)
```

**Comment by nicholas-sly** [comment]
I was having a similar issue.  Trying to change and save the config kept resulting in an error.  I restored the default config (which seemed exactly the same as my original config), and it started up just fine.

This is using version 0.2.0 of the add-on and 0.94.2 of hassio.

Hope this helps.

**Comment by jakobdettner** [comment]
For me it helped to hit: "Reset to defaults" in the config.

**Comment by fbartels** [comment]
Here the same. App only did start after reset of settings. No visible error message in home assistant when pressing start, but nothing happened.

**Comment by Jeltel** [comment]
With the new version (0.3.0) it does indeed start after resetting the settings and re-doing the changes I had.

**Comment by frenck** [comment]
The add-on settings changed in 0.2.0, you need to update the settings of the add-on to match. Unfortunately, Hass.io does not seem to update these settings anymore.

However, this is out of my hands.

**Comment by jerrychong25** [comment]
> The add-on settings changed in 0.2.0, you need to update the settings of the add-on to match. Unfortunately, Hass.io does not seem to update these settings anymore.
> 
> However, this is out of my hands.

Noted and thanks
