### ISSUE TITLE
after update to 027bd8a get a error

### ISSUE THREAD

**Issue by poudenes** [hassio-addons/addon-grocy#76]
Home Assistant 0.107.7
Frontend version: 20200318.1 - latest
CustomUI: 20190518

After upgrade to 027bd8a I get this error:

```
404 Not Found
The application could not run because of the following error:

Details

Type: Slim\Exception\HttpNotFoundException
Code: 404
Message: Not found.
File: /var/www/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php
Line: 93
Trace

#0 /var/www/grocy/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Slim\Middleware\RoutingMiddleware->performRouting(Object(Slim\Http\ServerRequest))
#1 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\RoutingMiddleware->process(Object(Slim\Http\ServerRequest), Object(Slim\Routing\RouteRunner))
#2 /var/www/grocy/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(98): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#3 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(140): Slim\Middleware\ErrorMiddleware->process(Object(Slim\Http\ServerRequest), Object(class@anonymous))
#4 /var/www/grocy/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\Http\ServerRequest))
#5 /var/www/grocy/vendor/slim/slim/Slim/App.php(211): Slim\MiddlewareDispatcher->handle(Object(Slim\Http\ServerRequest))
#6 /var/www/grocy/vendor/slim/slim/Slim/App.php(195): Slim\App->handle(Object(Slim\Http\ServerRequest))
#7 /var/www/grocy/app.php(81): Slim\App->run()
#8 /var/www/grocy/public/index.php(3): require_once('/var/www/grocy/...')
#9 {main}
Go Back
```

Uninstalled it and reinstalled it give me same error

**Comment by frenck** [comment]
That can happen on edge, which is a dev version.
It is the reason why this warning is on the install page if you install an edge add-on:

![image](https://user-images.githubusercontent.com/195327/78089307-529e1780-73c7-11ea-87ae-b52ff9f46325.png)
